exrate2020/chat/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),

]

exrate2020/exrate2020/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from nichiei.views import ContactView
import debug_toolbar


handler500 = 'authentication.views.error_500'

urlpatterns = [
    path('i18n/', include("django.conf.urls.i18n")),
    path('__debug__/', include(debug_toolbar.urls)),
    path("", TemplateView.as_view(template_name="nichiei/index.html"), name="top"),
    path("company/", TemplateView.as_view(template_name="nichiei/company.html"), name="company"),
    path("services/", TemplateView.as_view(template_name="nichiei/services.html"), name="services"),
    path("contact/", ContactView.as_view(), name="contact"),

    path('admin/', admin.site.urls),
    path("apiauth/", include("authentication.urls")),
    path("webauth/", include("web_auth.urls")),
    path('accounts/', include('allauth.urls')),

    path('back/store/', include('store.urls')),
    path('chat/', include('chat.urls')),

    path('qr_code/', include('qr_code.urls', namespace="qr_code")),

]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exrate2020/store/urls.py
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.cache import cache_page
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.conf import settings
from rest_framework.routers import DefaultRouter
from .viewsets import ShippingAddressViewSet, OrderViewSet, \
    MarginViewSet, ProductViewSet, PingoOrderViewSet, PingoItemViewSet, NewProductViewSet

from .views import (
    ProductView,
    SearchProductView,
    HomeView,
    OrderSummaryView,
    CheckoutView,
    Pingo_Checkout,
    ShoppingCartOperation,
    ShippingAddressAPIView,
    ProductAPIView,
    OrderListView,
    MarginListView,
    AddressBookListView,

    CategoryAPIView,
    # CategoryProductAPIView,

    show_dashboard,
    export_pdf_order,
)

app_name = 'store'
CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)

router = DefaultRouter()
router.register("shippingadress", ShippingAddressViewSet, basename="shippingaddress")
router.register("orders", OrderViewSet, basename="orders")
router.register("margins", MarginViewSet, basename="margins")
router.register("products", ProductViewSet, basename="products")
router.register("newproducts", NewProductViewSet, basename="newproducts")
router.register("pingo_orders", PingoOrderViewSet, basename="pingo_orders")
router.register("pingo_items", PingoItemViewSet, basename="pingo_items")


urlpatterns = [
    path("api/", include((router.urls, "store"), namespace="nishiei_ship")),
    path('', cache_page(CACHE_TTL)(HomeView.as_view()), name='home'),
    path('product/<int:pk>/', ProductView.as_view(), name='product'),
    path('search-product/', csrf_exempt(SearchProductView.as_view()), name='search-product'),
    path('order-summary/', OrderSummaryView.as_view(),
         name='order-summary'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('pingo_checkout/<int:pingoitem_id>/', Pingo_Checkout, name='pingo_checkout'),

    path('api/shoppingcart/', csrf_exempt(ShoppingCartOperation.as_view()), name='api-shoppingcart'),
    path('api/product/get/', csrf_exempt(ProductAPIView.as_view()), name='api-get-product'),
    path('api/categories/', csrf_exempt(CategoryAPIView.as_view()), name='api-get-categories'),
    # path('api/category/products/', csrf_exempt(CategoryProductAPIView.as_view()), name='api-get-category_products'),

    # account related
    # path('account/shippingaddress/', ShippingAddressAPIView.as_view(), name="my_shippingaddress"),
    path('account/orders/', OrderListView.as_view(), name="my_orders"),
    path('account/margins/', MarginListView.as_view(), name="my_margins"),
    path('account/dashboard/', show_dashboard, name="my_dashboard"),
    path('account/addressbook/', AddressBookListView.as_view(), name="my_addressbook"),

    path('export_pdf/<uuid:slug>/', export_pdf_order, name="export_order_pdf"),

]

exrate2020/templates/shop/accounts/addressbook.html
{% extends 'shop/base.html' %}
{% load static %}
{% load humanize %}
{% load store_tags %}

{% block headerscript %}{% endblock headerscript%}
{% block content %}

		<!-- Page Title
		============================================= -->
		<section id="page-title">

			<div class="container clearfix">
				<h1>Address Book</h1>
                <ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="#">Home</a></li>
					<li class="breadcrumb-item"><a href="#">Filters</a></li>
					<li class="breadcrumb-item active" aria-current="page">Shop Filter</li>
				</ol>
			</div>

		</section><!-- #page-title end -->

    		<!-- Content
		============================================= -->
		<section id="content">
			<div class="content-wrap">
				<div class="container clearfix">

					<div class="row gutter-40 col-mb-80">
						<!-- Post Content
						============================================= -->
                        <div class="postcontent col-lg-12">
                                <div id="shippingaddress_edit">
                                    <Shippingaddressedit></Shippingaddressedit>
                                </div>
                        </div>
					</div>

				</div>
			</div>
		</section><!-- #content end -->


{% endblock content%}

{% block footerscript_last %}

{% endblock footerscript_last%}

exrate2020/templates/shop/accounts/dashboard.html
{% extends 'shop/base.html' %}
{% load static %}
{% load humanize %}
{% load mptt_tags %}
{% load store_tags %}
{% load qr_code %}


{% block headerscript %}{% endblock headerscript%}
{% block content %}

		<!-- Page Title
		============================================= -->
		<section id="page-title">

			<div class="container clearfix">

				<h1>Dashboard</h1>
				<span>Products with Filter Functionality</span>
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="#">Home</a></li>
					<li class="breadcrumb-item"><a href="#">Filters</a></li>
					<li class="breadcrumb-item active" aria-current="page">Shop Filter</li>
				</ol>
			</div>

		</section><!-- #page-title end -->
    		<!-- Content
		============================================= -->
        <section id="content">
            <div class="content-wrap">
                <div class="container clearfix">
                    <div class="row gutter-40 col-mb-80">
                        <!-- Post Content
                        ============================================= -->
                        <div class="postcontent col-lg-6">
                            <h1>My Family Tree</h1>

                            <div id="membertree">
                                <MemberTree></MemberTree>
                            </div>
                        </div>

                        <div class="col-lg-6">
                            <div class="card">
                                <div class="card-header">Introcode</div>
                                <div class="card-body text-center">
                                    <img src="{% qr_url_from_text qrcode_introcode size='S' %}" alt="Hello World!">
{#                                    {% qrcode_url_from_text qrcode_introcode size='S' %}#}
                                    <p>{{ qrcode_introcode }}</p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </section><!-- #content end -->

{% endblock content%}

{% block footerscript_last %}

{% endblock footerscript_last%}

exrate2020/templates/shop/accounts/margins.html
{% extends 'shop/base.html' %}
{% load static %}
{% load humanize %}
{% load store_tags %}

{% block headerscript %}{% endblock headerscript%}
{% block content %}

		<!-- Page Title
		============================================= -->
		<section id="page-title">

			<div class="container clearfix">
				<h1>Margin History</h1>
				<span>Total Record: {{ margin_summary.total_count }}, Total Amount:  {{ margin_summary.total_amount  |intcomma:False  }}</span>
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="#">Home</a></li>
					<li class="breadcrumb-item"><a href="#">Filters</a></li>
					<li class="breadcrumb-item active" aria-current="page">Shop Filter</li>
				</ol>
			</div>

		</section><!-- #page-title end -->

    		<!-- Content
		============================================= -->
		<section id="content">
			<div class="content-wrap">
				<div class="container clearfix">

					<div class="row gutter-40 col-mb-80">
						<!-- Post Content
						============================================= -->
                        <div class="postcontent col-lg-12">

                            {% if margins.count %}
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Date</th>
                                    <th>LEVEl</th>
                                    <th>AMOUNT</th>
                                    <th>REFOUND</th>
                                    <th>PAID DATE</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for margin in margins %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ margin.order.ordered_date|naturalday }}</td>
                                        <td>{{ margin.level }}</td>
                                        <td>{{ margin.amount |intcomma:False  }}</td>
                                        <td>{{ margin.is_refound }}</td>
                                        <td>{{ margin.paid_at |naturalday }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>

                            <div class="pagination-container">
                                <div class="">
                                    Showing page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                                </div>
                                <ul class="pagination align-right float-right mr-auto">
                                    {% if page_obj.has_previous %}
                                        <li {% if page_obj.number == 1 %} class="page-item active" {% endif %}>
                                            <a class="page-link" href="?page=1">&laquo;1</a></li>
                                        <li class="page-item">
                                            <a class="page-link"
                                               href="?page={{ page_obj.previous_page_number }}">Previous</a>
                                        </li>
                                    {% endif %}

                                    {% if page_obj.has_next %}
                                        <li class="page-item"><a class="page-link"
                                                                 href="?page={{ page_obj.next_page_number }}">Next</a>
                                        </li>
                                        <li class="page-item"><a class="page-link"
                                                                 href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}
                                            &raquo;</a></li>
                                    {% endif %}


                                </ul>
                            </div>
                            {% else %}
                                <div class="alert alert-warning">
                                    <i class="icon-warning-sign"></i><strong>Warning!</strong> You have no orders!
                                </div>
                            {% endif %}
                        </div>
					</div>

				</div>
			</div>
		</section><!-- #content end -->


{% endblock content%}

{% block footerscript_last %}

{% endblock footerscript_last%}

exrate2020/templates/shop/accounts/orders.html
{% extends 'shop/base.html' %}
{% load static %}
{% load humanize %}
{% load store_tags %}

{% block headerscript %}{% endblock headerscript%}
{% block content %}

		<!-- Page Title
		============================================= -->
		<section id="page-title">

			<div class="container clearfix">
				<h1>Orders</h1>
				<span>Your orders are our honor!</span>
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="#">Home</a></li>
					<li class="breadcrumb-item"><a href="#">Filters</a></li>
					<li class="breadcrumb-item active" aria-current="page">Shop Filter</li>
				</ol>
			</div>

		</section><!-- #page-title end -->

    		<!-- Content
		============================================= -->
		<section id="content">
			<div class="content-wrap">
				<div class="container clearfix">

					<div class="row gutter-40 col-mb-80">
						<!-- Post Content
						============================================= -->
                        <div class="postcontent col-lg-12">

                            {% if orders.count %}
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Date</th>
                                    <th>STATUS</th>
                                    <th>Qty</th>
                                    <th>Total</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for order in orders %}
                                    <tr>
                                        <td>{{ forloop.counter }}-({{ order.id }})</td>
                                        <td>{{ order.ordered_date|naturalday }}</td>
                                        <td>{{ order.status }}</td>
                                        <td>{{ order.get_total_quantity }}</td>
                                        {#                                        <td>{{ order.get_total_quantity | multiply5:5 }},{%  multiply6 order.get_total_quantity 6  %}</td>#}
                                        <td>¥{{ order.get_total_price|intcomma:False }}</td>
                                        <td><a href="{% url 'store:export_order_pdf' slug=order.slug %}">Download</a></td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>

                            <div class="pagination-container">
                                <div class="">
                                    Showing page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                                </div>
                                <ul class="pagination align-right float-right mr-auto">
                                    {% if page_obj.has_previous %}
                                        <li {% if page_obj.number == 1 %} class="page-item active" {% endif %}>
                                            <a class="page-link" href="?page=1">&laquo;1</a></li>
                                        <li class="page-item">
                                            <a class="page-link"
                                               href="?page={{ page_obj.previous_page_number }}">Previous</a>
                                        </li>
                                    {% endif %}

                                    {% if page_obj.has_next %}
                                        <li class="page-item"><a class="page-link"
                                                                 href="?page={{ page_obj.next_page_number }}">Next</a>
                                        </li>
                                        <li class="page-item"><a class="page-link"
                                                                 href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}
                                            &raquo;</a></li>
                                    {% endif %}


                                </ul>
                            </div>
                            {% else %}
                                <div class="alert alert-warning">
                                    <i class="icon-warning-sign"></i><strong>Warning!</strong> You have no orders!
                                </div>
                            {% endif %}
                        </div><!-- .postcontent end -->
					</div>

				</div>
			</div>
		</section><!-- #content end -->


{% endblock content%}

{% block footerscript_last %}

{% endblock footerscript_last%}